### PR TITLE
Adds segment cleanup code

### PR DESCRIPTION
**Pull request by sarahdudek**
Not even sure we really need this...

@ltyomkin @minhahoang @LuisFlosi Lmk what you all think.

### CODE REVIEW

**Comment by LuisFlosi** [comment]
> Not even sure we really need this...
> 
> @ltyomkin @minhahoang @LuisFlosi Lmk what you all think.

If I understand corretly you just imported into python and then exported? Were there no changes to be made? If not, then yeah we wouldn't need it.

**Comment by LuisFlosi** [comment]
@sarahdudek thinking about this, I think we need to at least change column names so they match our DW names (to make it easier to import later)

**Review by LuisFlosi — APPROVED** [review]
Awesome! Ready to merge?

**Comment by sarahdudek** [comment]
Meh don't feel like doing the conflict resolves so gonna trash this and merge a clean one.

**Pull request closed without merging**
